name: Determine minimal project list
description: Determine the minimal project list with only those modules required based on changes

inputs:
  changed_files:
    description: A space-delimited list of the files that were changed
    required: true

outputs:
  project_list:
    description: A comma-delimited list of the projects that need to be rebuilt
    value: ${{ steps.create-project-list.outputs.project_list }}

runs:
  using: composite
  steps:

    - id: create-project-list
      name: Create project list
      shell: bash
      run: |
        echo "Starting: create_project_list.sh"
        source $GITHUB_ACTION_PATH/create_project_list.sh
        create_project_list ${{ inputs.changed_files }} 
        echo "Finished: create_project_list.sh in $SECONDS seconds"
