# This workflow will run tests within the shared-workflows

name: BATS tests of actions/workflows

on:
  push:
    branches-ignore: [ ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.0

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run BATS tests of determine-minimal-project-list
        run: |
          cd actions/determine-minimal-project-list/tests
          /usr/bin/env bats actions/determine-minimal-project-list/tests/test_script.bats
